hostname: localhost
datasets:

max_chunks_per_stream: 1000
max_parallel_streams: 10000
    
# DO NOT CHANGE BELOW THIS LINE. CLOUD API WILL NOT WORK
sqd_network:
  datasets: https://cdn.subsquid.io/sqd-network/datasets.yml
  serve: "all"
