available_datasets:
  ethereum-mainnet: "s3://ethereum-mainnet"
  arbitrum-one: "s3://arbitrum-one"
  base-mainnet: "s3://base-1"
  binance-mainnet: "s3://binance-mainnet"
  ethereum-sepolia: "s3://ethereum-sepolia-1"
  polygon-mainnet: "s3://polygon-mainnet-1"
  polygon-zkevm-mainnet: "s3://polygon-zkevm-mainnet-traceless"
  zksync-mainnet: "s3://zksync-mainnet-1"
